"""Building the no-install version.

Everything this repository does is either a prompt or a rule, and both are just
text. So the same source files that drive the CLI can be packed into a Claude
Project: paste one file into the project instructions, upload four knowledge
files, and the whole lifecycle runs in a conversation with nothing installed.

The bundle is **generated, never hand-maintained**. An agent prompt edited in
`agents/` flows into the project pack on the next build, and CI fails if the
committed pack is stale. Two copies of the same prompt drifting apart would be
the worst outcome here — the person using the Project would be running a version
of the reviewer that no longer matches the one under test.

What is honestly lost without Python is stated in the pack itself rather than
buried: the deterministic checks stop being deterministic. A model following a
banned-word list is careful; a regex is exact. The Project is the right choice
for someone who needs the work done today, and the CLI is the right choice for
anyone who needs numbers they can defend over time.
"""

from __future__ import annotations

from pathlib import Path

import yaml

from . import registry

ROOT = Path(__file__).resolve().parent.parent
REFERENCE = ROOT / "reference"

GENERATED = "<!-- generated by `colorteam project build` — edit the source, not this file -->"


def _agents_pack() -> str:
    agents = registry.load_all()
    parts = [
        GENERATED,
        "# The ten agents",
        "",
        "Each heading below is one stage of the pursuit lifecycle. When the "
        "operator names a stage, adopt that role completely for that turn and "
        "produce the output it specifies — nothing more, nothing less.",
        "",
        "| Stage | Agent | What it does |",
        "| --- | --- | --- |",
    ]
    for agent in agents.values():
        parts.append(f"| {agent.stage} | **{agent.name}** | {agent.purpose} |")
    parts.append("")

    for agent in agents.values():
        parts.extend([
            "---",
            "",
            f"## {agent.name}",
            "",
            f"**Stage:** {agent.stage}  ",
            f"**Inputs:** {', '.join(agent.inputs) if agent.inputs else 'the document supplied'}  ",
            f"**Output:** {' '.join(agent.output.split())}",
            "",
            agent.prompt,
            "",
        ])
    return "\n".join(parts)


def _checks_pack() -> str:
    rules = yaml.safe_load((REFERENCE / "style-rules.yaml").read_text(encoding="utf-8"))

    def table(entries, heading, why_column="Why it is a finding"):
        lines = [f"### {heading}", "", f"| Term | Severity | {why_column} |",
                 "| --- | --- | --- |"]
        for entry in entries or []:
            lines.append(
                f"| `{entry['term']}` | {entry.get('severity', 'medium')} | {entry['why']} |"
            )
        lines.append("")
        return lines

    thresholds = rules.get("thresholds", {})
    parts = [
        GENERATED,
        "# The checks",
        "",
        "These are the checks that run without judgment. In the command-line "
        "version they are executed by code and produce the identical result "
        "every time. Here you execute them, which means being **mechanical on "
        "purpose**: work through the lists, do not skim, and do not exercise "
        "taste about whether a finding matters. Taste is what the review stages "
        "are for.",
        "",
        "## Check 1 — Language",
        "",
        "Report every occurrence with its line or section, the term, the "
        "severity, and a replacement written in the document's own voice. Sort "
        "by severity, then by position. Count them, and state the counts — the "
        "count is the number a team tracks across drafts.",
        "",
    ]
    parts += table(rules.get("prohibited"), "Prohibited — high severity by default")
    parts += table(rules.get("overclaim"), "Unsupported claims")
    parts += table(rules.get("hedge"), "Hedges")
    parts += [
        "### Passive voice",
        "",
        "A form of *to be* (" + ", ".join(rules["passive"]["be_forms"]) + ") followed "
        "by a past participle. " + rules["passive"]["why"] + " Supply the active "
        "rewrite with the actor named. Do not flag it where the actor is genuinely "
        "unknown or the document type requires it.",
        "",
        "### The gate",
        "",
        f"- More than **{thresholds.get('high_per_kwords', 0)}** high-severity "
        "findings per 1,000 words → **HOLD**",
        f"- More than **{thresholds.get('medium_per_kwords', 3)}** medium-severity "
        "findings per 1,000 words → **HOLD**",
        "- Otherwise **PASS**",
        "",
        "Normalize per 1,000 words. Raw counts reward writing less, which is not "
        "the goal.",
        "",
        "## Check 2 — Coverage",
        "",
        "Against the compliance matrix, for every row a reviewer has not flagged "
        "as `mis-extracted`, `duplicate`, or `not-a-requirement`:",
        "",
        "1. Is the requirement addressed? It counts as addressed if the draft "
        "cites its ID, or if the outline section it was assigned to exists in "
        "the draft with substantive content under it.",
        "2. Report every unaddressed requirement by ID and text.",
        "3. **Mark separately any unaddressed requirement tied to an evaluation "
        "criterion.** Those are lost points, not merely missing text.",
        "",
        "A row that states a *limit* rather than an obligation — \"the Technical "
        "Volume shall not exceed 25 pages\" — is satisfied by the page math "
        "below, not by prose. Do not report it as unaddressed.",
        "",
        "Any unaddressed requirement → **HOLD**.",
        "",
        "## Check 3 — Page math",
        "",
        "Estimate at **500 words per page** (12pt serif, single spaced, one-inch "
        "margins, before graphics displace text). Count the words, divide, and "
        "state the estimate as an estimate. Check the whole document against its "
        "stated limit, and each section against any limit its requirements carry.",
        "",
        "Over any limit → **HOLD**.",
        "",
        "## The rule that governs all three",
        "",
        "**These gates are a veto, not a vote.** A proposal that misses a "
        "requirement or busts a page limit is non-responsive no matter how well "
        "it reads. Never raise a judgment score to compensate for a failed gate, "
        "and never soften a gate result because the writing is good.",
        "",
    ]
    return "\n".join(parts)


def _rubric_pack() -> str:
    rubric = yaml.safe_load((REFERENCE / "score-rubric.yaml").read_text(encoding="utf-8"))
    parts = [
        GENERATED,
        "# The scoring rubric",
        "",
        "Used by **SCORE**. It governs only what judgment decides. The checks "
        "already settled coverage, page math, and language — do not re-grade "
        "them here.",
        "",
        "## Scale",
        "",
        "| Score | Meaning |",
        "| --- | --- |",
    ]
    for score, text in sorted(rubric["descriptors"].items(), reverse=True):
        parts.append(f"| **{score}** | {text} |")

    parts += ["", "## Dimensions", "",
              "| Dimension | Weight | What a 5 looks like |", "| --- | --- | --- |"]
    for name, spec in rubric["dimensions"].items():
        parts.append(
            f"| **{name}** | {spec['weight']} | {' '.join(spec['what_five_looks_like'].split())} |"
        )

    limits = rubric["thresholds"]
    parts += [
        "",
        "## Arithmetic",
        "",
        "- Weighted score = Σ(weight × score), on the 1–5 scale.",
        "- Normalized = (weighted − 1) ÷ 4, on 0–1.",
        f"- **Pass** at normalized ≥ **{limits['pass_normalized']}** "
        f"(weighted {1 + 4 * limits['pass_normalized']:.1f} of 5), with no "
        f"dimension below {limits['no_dimension_below']} and no section below "
        f"{limits['no_section_below']}.",
        f"- Sections scoring **{limits['revise_at_or_below']} or below** go on "
        "the revision worklist, weakest first.",
        f"- Within **{limits['borderline_band']}** of the threshold is "
        "borderline: score it a second time and average. Judgment scores wobble.",
        "",
        "## Rules",
        "",
    ]
    for rule in rubric["rules"]:
        parts.append(f"- {rule}")
    parts += [
        "",
        "Score every section, not just the weak ones — a section you skip is a "
        "section nobody revises.",
        "",
    ]
    return "\n".join(parts)


def _schema_pack() -> str:
    body = (REFERENCE / "compliance-schema.md").read_text(encoding="utf-8")
    return GENERATED + "\n\n" + body


def instructions() -> str:
    """The text that goes in the Project's custom instructions box."""
    agents = registry.load_all()
    stages = " → ".join(a.name for a in agents.values())
    return f"""{GENERATED}

You run a federal proposal shop. The operator brings you a solicitation and, over
several turns, you take it to a red team draft. Four uploaded files define how:
`agents.md` (the ten roles), `checks.md` (the mechanical checks), `rubric.md`
(the scoring rubric), and `schema.md` (the compliance matrix format).

## How a turn works

The operator names a stage. Adopt that role from `agents.md` completely, follow
its instructions, and produce exactly the output it specifies. One stage per
turn. Never run the next stage because it seems helpful — every stage is a
decision point that belongs to a human, and chaining them silently is how a
mistake in the matrix becomes a mistake in the whole proposal.

The lifecycle, in order:

{stages}

Short commands the operator may use: `/classify` `/gate` `/shred` `/outline`
`/draft` `/pink` `/red` `/score` `/redline` `/debrief`, plus `/check` for the
mechanical checks, `/matrix` to re-emit the compliance matrix, and `/assemble`
to produce the finished document.

If the operator asks for something ambiguous, ask which stage they mean rather
than guessing. If they ask for a stage whose inputs are missing — PINK without a
compliance matrix, RED without reviewer comments — say what is missing and offer
to proceed with a stated limitation.

## The rule that outranks every other rule

**Never invent a fact.** Not a contract number, percentage, date, customer,
staffing level, past performance reference, certification, or metric. Not as an
example, not "for illustration."

Where a fact is missing, emit a marker and write the sentence around it:

- `[PROOF NEEDED: on-time delivery rate for a comparable contract]`
- `[SME INPUT: how the diagnostic tool isolates faults]`
- `[PAST PERFORMANCE: contract of similar scope, last 5 years]`

Then list every marker in a **Placeholder Manifest** — the marker, its section,
what would close it, and the owner role — sorted by evaluation weight blocked.

A fabricated number reads plausibly, survives review, reaches the government, and
becomes a false statement in a submitted offer. It is the one failure this
project must not have. A marker is never an embarrassment; an invented figure is.

## The evidence base

Documents the operator uploads to this project — capability statements, resumes,
past performance, prior proposals won and lost, pricing history — are the **only**
facts available to you. When you use one, name the file in the text so a reviewer
can verify it in seconds. A claim you cannot attribute to an uploaded document is
a claim you mark, not one you assert, however reasonable it sounds.

If nothing relevant is uploaded, say so plainly and draft with markers rather than
filling the gap from general knowledge.

## The checks are a veto

`checks.md` holds three mechanical checks: language, requirement coverage, and
page math. Run them exactly as written — work the lists, do not skim, do not
exercise taste about whether a finding matters.

**A failed check produces HOLD regardless of how well the proposal reads.** Never
raise a judgment score to compensate, and never soften a check result because the
writing is good. A proposal that misses a requirement is non-responsive.

Be honest about what you are: a careful reader working a list, not a regex. State
your counts, and if you are uncertain whether something matched, report it rather
than dropping it.

## Output conventions

- The compliance matrix is always a Markdown table in the `schema.md` format, with
  stable IDs. Never renumber IDs — the outline, the draft, and every review
  comment reference them.
- Figures are fenced ```mermaid blocks under a `### Figure N — Title` heading,
  each with an **Action caption** stating what the figure proves and why the
  customer benefits. A caption that merely labels the figure has wasted the
  most-read line on the page.
- For anything the operator will keep — a draft, a matrix, an assembled document —
  produce it as an artifact so they can copy it into Word or Excel cleanly.
- When a document is finished, offer the assembled version: the draft, then the
  compliance matrix, then traceability naming every unaddressed requirement, then
  the open items. Keep every marker visible in the body. An unclosed marker
  reaching a customer is a fabrication risk, and it must be impossible to miss.

## Tone

You are a colleague who has run these pursuits, not an assistant. Say plainly
when a bid looks unwinnable, when a section should be rewritten rather than
polished, and when a reviewer's comment would make the proposal worse. The most
valuable sentence you produce is usually the uncomfortable one.
"""


def readme() -> str:
    return f"""{GENERATED}

# colorteam as a Claude Project

The same ten agents, the same checks, the same rubric — with nothing installed.
Everything here is either a prompt or a rule, and both are text, so the whole
lifecycle runs in a conversation.

## Setup, about five minutes

1. In Claude, create a new Project. Name it something like *Proposal Color Team*.
2. Open the project's **instructions** and paste in all of `instructions.md`.
3. Upload these four files to the project's knowledge:
   - `agents.md` — the ten roles
   - `checks.md` — language, coverage, page math
   - `rubric.md` — the scoring rubric
   - `schema.md` — the compliance matrix format
4. Upload your evidence base: capability statements, resumes, past performance,
   prior proposals won and lost, pricing history. These stay inside your project.
5. Start a conversation, attach a solicitation, and type `/classify`.

## Using it

```
/classify        what kind of solicitation is this, and what does it want
/gate            bid, watch, or decline — and the three questions that would change it
/shred           the compliance matrix
/outline         annotated outline with page budgets and win themes
/draft           a pink-team draft, with markers where evidence is missing
/check           language, coverage, and page math
/pink            the pink team review
/red             a red team draft from a commented pink draft
/score           scored the way an evaluator would
/redline         final quality pass
/assemble        the full document with its appendices
/debrief         turn a government debrief into corrective actions
```

One stage per turn, and a human decision between every one. That is the design,
not a limitation.

## What you give up

**The checks stop being deterministic.** In the command-line version, the
language check is a regular expression and the coverage check is arithmetic:
identical input produces an identical result, every time, forever. Here, a
careful reader works the same lists. That is good enough to find the problems and
not good enough to build a metric on — if the number moves between two runs of
the same draft, you cannot tell whether the draft changed or the reader did.

So: use the Project to do the work. Use the CLI when you need a number you will
put in front of leadership, or a check that runs in CI on every commit.

**No spreadsheet round trip, and no .docx out.** The matrix comes back as a
Markdown table you can paste into Excel; the assembled document is an artifact
you paste into Word.

## Keeping it current

This folder is generated from the same files the CLI uses:

```bash
python -m colorteam project build
```

Do not edit these files by hand. Edit `agents/*.md` or `reference/*` and rebuild —
CI fails if the committed pack has drifted from its sources. Two copies of the
same reviewer prompt disagreeing is the worst thing that could happen here.
"""


FILES = {
    "README.md": readme,
    "instructions.md": instructions,
    "knowledge/agents.md": _agents_pack,
    "knowledge/checks.md": _checks_pack,
    "knowledge/rubric.md": _rubric_pack,
    "knowledge/schema.md": _schema_pack,
}


def build(out_dir: Path | str = ROOT / "project") -> list[Path]:
    out_dir = Path(out_dir)
    written = []
    for name, generator in FILES.items():
        path = out_dir / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(generator(), encoding="utf-8")
        written.append(path)
    return written


def is_current(out_dir: Path | str = ROOT / "project") -> tuple[bool, list[str]]:
    """Has anything drifted from its source? Used by CI."""
    out_dir = Path(out_dir)
    stale = []
    for name, generator in FILES.items():
        path = out_dir / name
        if not path.exists():
            stale.append(f"{name} (missing)")
        elif path.read_text(encoding="utf-8") != generator():
            stale.append(name)
    return not stale, stale
